DROP SEQUENCE S_NOTE_ID;
DROP TABLE NOTE;

CREATE TABLE NOTE (
	NOTE_ID NUMBER(5),
	TITLE VARCHAR(20),
    PRIMARY KEY (NOTE_ID)
);

CREATE SEQUENCE S_NOTE_ID
INCREMENT BY 1
START WITH 0
MINVALUE 0
MAXVALUE 99999;

INSERT INTO NOTE (NOTE_ID, TITLE) VALUES (S_NOTE_ID.NEXTVAL, 'Hello World!');
INSERT INTO NOTE (NOTE_ID, TITLE) VALUES (S_NOTE_ID.NEXTVAL, 'Hello');
INSERT INTO NOTE (NOTE_ID, TITLE) VALUES (S_NOTE_ID.NEXTVAL, 'World');
INSERT INTO NOTE (NOTE_ID, TITLE) VALUES (S_NOTE_ID.NEXTVAL, '!');

COMMIT;